input:
  keyMappings:
    # spinLeft: [Z, ArrowUp]
    # spinRight: [X]
    # down: [ArrowDown]
    # left: [ArrowLeft]
    # right: [ArrowRight]
    # place: [Space]
    # pause: [ESC, p]
    forward: [W, ArrowUp]
    left: [A, ArrowLeft]
    back: [S, ArrowDown]
    right: [D, ArrowRight]
    turn: [Space]
    quit: [ESC]
    zoomIn: [ScrollUp]
    zoomOut: [ScrollDown]
  scriptPath: input.lua
  resourcePath: ../res/

window:
  targetFPS: 60
  windowWidth: 440
  windowHeight: 840
